import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './context/AuthContext'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] })

export const metadata: Metadata = {
  title: 'Adote.me',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.className} bg-purple-500 text-white overflow-hidden`}
      >
        <AuthProvider>
          <div className="min-h-screen h-screen flex flex-col justify-center items-center p-4">
            <main className="flex-1 w-full max-w-lg mx-auto p-4">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
